/*
 * File: app/store/BattlesLocalStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.BattlesLocalStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Battle'
    ],

    config: {
        data: [
            [
                1,
                2,
                'John Doe',
                'William Smith',
                'Chennai Super Kings',
                'Royal Challengers',
                70,
                30,
                'http://s3.amazonaws.com/h2htv/media/rugbyh2h/players/mac-hull/square.png',
                'http://s3.amazonaws.com/h2htv/media/rugbyh2h/players/zahid-jethani/square.png'
            ],
            [
                1,
                3,
                'Alex Stewart',
                'Mornie Morkel',
                'Rajastan Royals',
                'Mumbai Indians',
                60,
                40,
                'http://s3.amazonaws.com/h2htv/media/rugbyh2h/players/zahid-jethani/square.png',
                'http://s3.amazonaws.com/h2htv/media/rugbyh2h/players/mac-hull/square.png'
            ]
        ],
        model: 'MyApp.model.Battle',
        storeId: 'BattlesLocalStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});