/*
 * File: app/store/DivisionsLocalStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.DivisionsLocalStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Division'
    ],

    config: {
        data: [
            [
                'Division 1',
                1,
                1
            ],
            [
                'Division 2',
                1,
                2
            ],
            [
                'Division 3',
                2,
                3
            ],
            [
                'Division 4',
                2,
                4
            ]
        ],
        model: 'MyApp.model.Division',
        storeId: 'DivisionsLocalStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});