/*
 * File: app/store/SpotlightsLocalStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.SpotlightsLocalStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Spotlight'
    ],

    config: {
        data: [
            [
                'John Doe',
                'Chennai Super Kings',
                'Chennai',
                'Height:6\'2, Weight: 75 Kgs',
                'Rank:#1',
                './images/player-a.png'
            ],
            [
                'William Smith',
                'Royal Challengers',
                'Bangalore',
                'Height:6\'4, Weight: 85 Kgs',
                'Rank:#3',
                './images/player-b.png'
            ]
        ],
        model: 'MyApp.model.Spotlight',
        storeId: 'SpotlightsLocalStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});