/*
 * File: app/store/TeamsLocalStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TeamsLocalStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Team'
    ],

    config: {
        data: [
            [
                1,
                1,
                'Team Takeover(DC)',
                '',
                14,
                3
            ],
            [
                2,
                1,
                'Oakland Soldiers(CA)',
                '',
                3,
                12
            ],
            [
                3,
                2,
                'Spiece',
                '',
                11,
                6
            ],
            [
                4,
                3,
                'Loisiana Select',
                '',
                17,
                2
            ]
        ],
        model: 'MyApp.model.Team',
        storeId: 'TeamsLocalStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});