/*
 * File: app/store/TournamentsLocalStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TournamentsLocalStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Tournament'
    ],

    config: {
        data: [
            [
                './images/icon200-a.png',
                './images/icon-a.png',
                'Tournament A',
                'Chennai',
                'Aug 20-28',
                1,
                'http://google.com'
            ],
            [
                './images/icon200-b.png',
                './images/icon-b.png',
                'Tournament B',
                'Bangalore',
                'May 18-23',
                2,
                'http://google.com'
            ]
        ],
        model: 'MyApp.model.Tournament',
        storeId: 'TournamentsLocalStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});