/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    requires: [
        'MyApp.model.override.User'
    ],

    models: [
        'Session',
        'User',
        'Battle',
        'Tournament',
        'Division',
        'Spotlight',
        'Team',
        'ScoreDisplay'
    ],
    stores: [
        'UsersLocalStore',
        'BattlesLocalStore',
        'SessionsLocalStore',
        'TournamentsLocalStore',
        'DivisionsLocalStore',
        'SpotlightsLocalStore',
        'TeamsLocalStore',
        'ScoresDisplayStore',
        'UsersStore',
        'SessionsStore',
        'BattlesStore',
        'TournamentsStore',
        'DivisionsStore',
        'TeamsStore',
        'SpotlightsStore'
    ],
    views: [
        'MyNavigationView',
        'RegistrationsContainer',
        'MainTab',
        'BattlePanel',
        'LoginContainer',
        'ScorePanel',
        'SchedulePanel',
        'SpotlightPanel'
    ],
    name: 'MyApp',
    controllers: [
        'LoginController',
        'UsersController',
        'BattlesController',
        'ScoresController',
        'SchedulesController',
        'SpotlightsController',
        'MainController'
    ],

    launch: function() {

        Ext.create('MyApp.view.MyNavigationView', {fullscreen: true});
    }

});
