/*
 * File: app/controller/BattlesController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.BattlesController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            battlePages: '#battle_pages'
        },

        control: {
            "#battle_pages": {
                initialize: 'onCarouselInitialize'
            },
            "#h2h_link": {
                tap: 'onH2HLinkTap'
            },
            "#submit_video_link": {
                tap: 'onSubmitVideoLinkTap'
            }
        }
    },

    onCarouselInitialize: function(component, options) {
        var battleStore = Ext.data.StoreManager.lookup('BattlesStore');
        for(i=0;i<battleStore.getCount();i++) {
            var battlePanel = Ext.create("MyApp.view.BattlePanel");
            battlePanel.down("#battle_id").setHtml("Round : " + battleStore.getAt(i).get("round_id") + " - Battle : " + battleStore.getAt(i).get("battle_id"));
            battlePanel.down("#left_player_name").setHtml(battleStore.getAt(i).get("left_player_name"));
            battlePanel.down("#right_player_name").setHtml(battleStore.getAt(i).get("right_player_name"));                
            battlePanel.down("#left_player_description").setHtml(battleStore.getAt(i).get("left_player_description"));                    
            battlePanel.down("#right_player_description").setHtml(battleStore.getAt(i).get("right_player_description"));                    
            battlePanel.down("#left_player_vote_percent").setHtml(battleStore.getAt(i).get("left_player_vote_percent") + "%");                    
            battlePanel.down("#right_player_vote_percent").setHtml(battleStore.getAt(i).get("right_player_vote_percent") + "%");                    
            battlePanel.down("#left_player_image_url").setSrc(battleStore.getAt(i).get("left_player_image_url"));                    
            battlePanel.down("#right_player_image_url").setSrc(battleStore.getAt(i).get("right_player_image_url"));                    
            this.getBattlePages().add([battlePanel]);
        }
    },

    onH2HLinkTap: function(button, e, options) {
        window.open("http://h2h.bownce.com?rho_open_target=_blank");
    },

    onSubmitVideoLinkTap: function(button, e, options) {
        window.open("http://h2h.bownce.com/static/submit_bownce_videos.html?rho_open_target=_blank");
    }

});