/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.LoginController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            navView: '#nav_root',
            formLogin: '#loginForm'
        },

        control: {
            "#login": {
                tap: 'onLoginButtonTap'
            },
            "#login_action": {
                tap: 'onLogin'
            },
            "navigationview": {
                push: 'onNavigationviewPush'
            }
        }
    },

    onLoginButtonTap: function(button, e, options) {
        var login = Ext.create('MyApp.view.LoginContainer', {
        title: 'Login' });
        this.getNavView().push(login);


    },

    onLogin: function(button, e, options) {
        var sessionsStore = Ext.data.StoreManager.lookup('SessionsStore');
        var usersStore = Ext.data.StoreManager.lookup('UsersStore');
        values = this.getFormLogin().getValues();

        /*
        var user = usersStore.findRecord("email", values.email);
        if (!user || (user.get("password") != values.password)) {
        Ext.Msg.alert("Failure", "Invalid Login.  Please try again.");
        return;
        }
        */

        var session = Ext.create('MyApp.model.Session');
        session.set("email", values.email);
        session.set("password", values.password);
        //sessionsStore.add(session);
        var me = this;
        Ext.data.JsonP.request({
            url: 'http://app.bownce.com/login',
            callbackKey: 'callback',
            params: {
                "user[email]":  session.get("email"),
                "user[password]":  session.get("password")
            },
            success: function(result) {
                if (result.error)
                Ext.Msg.alert("Failure", result.error);
                else {
                    //            Ext.Msg.alert("Success", "Login Success!", function() {
                    refresh_stores(function() {
                        if (!me.mainTab) {
                            me.mainTab = Ext.create('MyApp.view.MainTab', {title: "H2H"});
                        }
                        me.getNavView().push(me.mainTab);
                        me.getNavView().getNavigationBar().setHeight(0);
                    });
                    //            });
                }
            },
            failure: function(result) {
                console.log(result);
                Ext.Msg.alert("Error", "Unexpected error occurred.\nPlease try again later.");
            }
        });


    },

    onNavigationviewPush: function(navigationView, view, options) {

    }

});