/*
 * File: app/controller/SpotlightsController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.SpotlightsController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            spotlightPages: '#spotlight_pages'
        }
    },

    refreshContents: function() {
        var spotlightsStore = Ext.data.StoreManager.lookup('SpotlightsStore');
        this.getSpotlightPages().removeAll();
        for(i=0;i<spotlightsStore.getCount();i++) {
            var spotlightPanel = Ext.create("MyApp.view.SpotlightPanel");
            spotlightPanel.down("#player_name").setHtml(spotlightsStore.getAt(i).get('player_name'));
            spotlightPanel.down("#player_team").setHtml(spotlightsStore.getAt(i).get('player_team'));
            spotlightPanel.down("#player_description").setHtml(spotlightsStore.getAt(i).get('player_description'));
            spotlightPanel.down("#player_physique").setHtml(spotlightsStore.getAt(i).get('player_physique'));
            spotlightPanel.down("#player_rank").setHtml(spotlightsStore.getAt(i).get('player_rank'));
            spotlightPanel.down("#player_image_url").setSrc(spotlightsStore.getAt(i).get('player_image_url'));
            spotlightPanel.down("#profile_link").on("tap", this.onProfileLinkTapped, this);
            this.getSpotlightPages().add([spotlightPanel]);
            this.getSpotlightPages().setActiveItem(0);    
        }
    },

    onProfileLinkTapped: function() {
        var record_index = this.getSpotlightPages().getActiveIndex();
        if (record_index < 0) {
            return;
        }
        var spotlightsStore = Ext.data.StoreManager.lookup('SpotlightsStore');
        var url = spotlightsStore.getAt(record_index).get("player_profile_url");
        if (url.indexOf("?") > 0)
        url += "&";
        else
        url += "?";
        window.open(url + "rho_open_target=_blank");
    }

});