/*
 * File: app/view/BattlePanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BattlePanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            align: 'center',
            pack: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'label',
                docked: 'top',
                html: 'Round #1 : Battle #2',
                itemId: 'battle_id',
                margin: 10,
                style: 'text-align:center;color:darkblue;font-weight:bold;font-size:25px;'
            },
            {
                xtype: 'panel',
                docked: 'top',
                margin: '0 3 0 3',
                minWidth: '95%',
                style: 'background-color:lightyellow;border:2px solid gray;border-radius:20px;',
                layout: {
                    type: 'vbox'
                },
                flex: 2,
                items: [
                    {
                        xtype: 'panel',
                        style: 'text-align:center',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 97,
                                itemId: 'left_player_image_url',
                                margin: 10,
                                width: 99,
                                src: 'http://s3.amazonaws.com/h2htv/media/rugbyh2h/players/zahid-jethani/square.png',
                                flex: 1
                            },
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 97,
                                itemId: 'right_player_image_url',
                                margin: 10,
                                width: 99,
                                src: 'http://s3.amazonaws.com/h2htv/media/rugbyh2h/players/mac-hull/square.png',
                                flex: 1
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        height: 10
                    },
                    {
                        xtype: 'panel',
                        margin: 0,
                        style: 'font-size:13px;font-weight:bold;text-align:center;',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'Left Player',
                                itemId: 'left_player_name',
                                margin: '0 10 0 10',
                                flex: 1
                            },
                            {
                                xtype: 'label',
                                docked: 'right',
                                html: 'Right Player',
                                itemId: 'right_player_name',
                                margin: '0 10 0 10',
                                flex: 1
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        style: 'font-size:12px;font-weight:bold;text-align:center;',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'Left Player Description',
                                itemId: 'left_player_description',
                                margin: '2 10',
                                flex: 1
                            },
                            {
                                xtype: 'label',
                                docked: 'right',
                                html: 'Right Player Description',
                                itemId: 'right_player_description',
                                margin: '2 10',
                                flex: 1
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        style: 'font-size:22px;font-weight:bold;text-align:center;color:green;',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: '60%',
                                itemId: 'left_player_vote_percent',
                                margin: '3 10 0 10',
                                flex: 1
                            },
                            {
                                xtype: 'label',
                                docked: 'right',
                                html: '40%',
                                itemId: 'right_player_vote_percent',
                                margin: '3 10 0 10',
                                flex: 1
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 20
            }
        ]
    }

});