/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyNavigationView', {
    extend: 'Ext.navigation.View',

    config: {
        itemId: 'nav_root',
        items: [
            {
                xtype: 'container',
                defaults: '{',
                layout: {
                    type: 'vbox'
                },
                title: 'Welcome to Bownce',
                items: [
                    {
                        xtype: 'panel',
                        docked: 'top',
                        height: '',
                        margin: 10,
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'vbox'
                        },
                        flex: 1,
                        items: [
                            {
                                xtype: 'image',
                                height: 95,
                                width: 271,
                                src: './images/bownce_logo.png'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        height: 177,
                        html: 'Connect Instantly',
                        margin: '0 20 0 20',
                        style: 'text-align:center;color:darkblue;font-weight:bold;font-size:22px;',
                        layout: {
                            type: 'vbox'
                        },
                        flex: 0.5,
                        items: [
                            {
                                xtype: 'label',
                                html: 'Showcase Your Game'
                            },
                            {
                                xtype: 'spacer',
                                height: 10
                            },
                            {
                                xtype: 'label',
                                html: 'Amplify Your Skills'
                            },
                            {
                                xtype: 'spacer',
                                height: 10
                            },
                            {
                                xtype: 'label'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        items: [
                            {
                                xtype: 'button',
                                id: 'login',
                                margin: 10,
                                ui: 'action',
                                text: 'Login'
                            },
                            {
                                xtype: 'button',
                                id: 'register',
                                margin: 10,
                                ui: 'action',
                                text: 'Register'
                            }
                        ]
                    }
                ]
            }
        ],
        navigationBar: {
            id: 'navbar',
            ui: 'light'
        }
    }

});