/*
 * File: app/view/SchedulePanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SchedulePanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            align: 'center',
            pack: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'label',
                html: 'Tournament Name',
                itemId: 'tournament_name',
                style: 'text-align:center;color:#002b54;font-weight:bold;font-size:22px;'
            },
            {
                xtype: 'panel',
                items: [
                    {
                        xtype: 'image',
                        docked: 'top',
                        height: 201,
                        itemId: 'tournament_logo',
                        ui: '',
                        width: 201,
                        src: './images/icon200.png'
                    }
                ]
            },
            {
                xtype: 'panel',
                style: 'text-align:center;color:gray;font-weight:bold;font-size:18px;',
                items: [
                    {
                        xtype: 'label',
                        html: 'New Jersey, NJ',
                        itemId: 'tournament_location'
                    },
                    {
                        xtype: 'label',
                        html: 'Aug 20 - 22',
                        itemId: 'tournament_dates'
                    },
                    {
                        xtype: 'spacer',
                        height: 5
                    }
                ]
            }
        ]
    }

});