/*
 * File: app/view/ScorePanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ScorePanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            align: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'panel',
                height: 64,
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'image',
                        height: 57,
                        itemId: 'tournament_logo',
                        width: 57,
                        src: './images/icon.png',
                        flex: 1
                    },
                    {
                        xtype: 'label',
                        html: 'Nike EYBL',
                        itemId: 'tournament_name',
                        margin: 20,
                        style: 'text-align:center;color:darkblue;font-weight:bold;font-size:22px;',
                        flex: 2
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'grid_panel',
                width: '100%',
                flex: 2
            },
            {
                xtype: 'panel',
                style: 'text-align:center;color:gray;font-weight:bold;font-size:18px;',
                items: [
                    {
                        xtype: 'label',
                        html: 'New Jersey, NJ',
                        itemId: 'tournament_location'
                    },
                    {
                        xtype: 'label',
                        html: 'Aug 20 - 22',
                        itemId: 'tournament_dates'
                    },
                    {
                        xtype: 'spacer',
                        height: 20
                    }
                ]
            }
        ]
    }

});