/*
 * File: app/view/SpotlightPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SpotlightPanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            align: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'panel',
                height: 323,
                margin: '5 0 0 0 ',
                style: 'background-color:#FFFFFF;border:2px solid #fCb040;border-radius:20px;text-align:center;color:gray;font-weight:bold;font-size:12px;',
                width: 307,
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'label',
                        docked: 'top',
                        html: 'Rasheed Sulaimon',
                        itemId: 'player_name',
                        style: 'color:#002b54;font-size:20px;'
                    },
                    {
                        xtype: 'label',
                        docked: 'top',
                        html: 'AAU Team: Houston Hoops;',
                        itemId: 'player_team'
                    },
                    {
                        xtype: 'label',
                        docked: 'top',
                        html: 'SG: Duke',
                        itemId: 'player_description'
                    },
                    {
                        xtype: 'label',
                        docked: 'top',
                        html: 'Body: 6\'3\'\', 175',
                        itemId: 'player_physique'
                    },
                    {
                        xtype: 'label',
                        docked: 'top',
                        html: 'Rank: #14,',
                        itemId: 'player_rank'
                    },
                    {
                        xtype: 'image',
                        docked: 'top',
                        height: 201,
                        itemId: 'player_image_url',
                        margin: '0 50 5 50',
                        ui: '',
                        width: 198,
                        src: './images/icon200.png'
                    },
                    {
                        xtype: 'button',
                        id: 'profile_link',
                        margin: '0 0 5 0',
                        style: 'font-style:italic;font-weight:lighter',
                        ui: 'action-round',
                        text: 'Click here to view this player\'s bownce profile'
                    }
                ]
            }
        ]
    }

});