/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.User', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            {
                name: 'email'
            },
            {
                name: 'password'
            },
            {
                name: 'password_confirmation'
            },
            {
                name: 'terms_flag'
            }
        ],
        validations: [
            {
                type: 'email',
                field: 'email',
                message: 'Email is not valid.'
            },
            {
                type: 'length',
                field: 'password',
                max: 8,
                min: 6,
                message: 'Password should be 4 to 8 characters.'
            },
            {
                type: 'presence',
                field: 'terms_flag'
            }
        ]
    }
});